# Generated by Django 3.0.7 on 2020-06-27 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1000, verbose_name="Название")),
                ("code", models.CharField(max_length=1000, unique=True, verbose_name="Код")),
                ("parent", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    to="orgunits.Organization",
                    verbose_name="Вышестоящая организация"),
                 ),
            ],
            options={
                "verbose_name": "Организации",
                "verbose_name_plural": "Организация",
                "ordering": ["name"],
            },
        ),
    ]
